### ISSUE TITLE
Create an example for demonstrating package use

### ISSUE THREAD

**Issue by atifcppprogrammer** [atifcppprogrammer/yflicks-yts#19]
Create an example program demonstrating how to use this package. This example program will serve two different purposes.

1. Providing a tutorial for the end-user on how to use this package.
2. Running an example program will notify us immediately if any changes on the website lead to breakages in our code.

For closing this issue provide both the example program and and a Github Action which runs the example program, every time a commit is pushed and or merge into `master`.

**Comment by gleed007** [comment]
kindly assign this issue to me.

**Comment by atifcppprogrammer** [comment]
@gleed007. Thanks for the pull request. Issue #5 has now been closed by #21, can you please sync your fork and add examples for the new methods too :+1:.
